---
- name: Update apt cache
  become: True
  apt:
    update_cache: yes
  tags: common

- name: Install PHPLint globally for PHP linting
  become: yes
  command: npm install -g phplint@v1.7.4
  tags: common

- name: Install System Packages
  become: True
  apt: pkg={{ item }} state=installed
  with_items:
    - php5.6-gd
    - clamav
    - python-setuptools
    - python-pip
  tags: common

- name: Install Python packages
  become: True
  command: pip install gitpython
  tags: common

- name: Configure PALANTIR_ENVIRONMENT variable
  lineinfile: dest=/home/vagrant/.profile state=present line='export PALANTIR_ENVIRONMENT="vagrant"'
  tags: common

- name: Copy gitignore
  copy: src=roles/common/templates/gitignore dest=/home/vagrant/.gitignore
  tags: common

- name: Configure global gitignore
  command: /usr/bin/git config --global core.excludesfile ~/.gitignore
  tags: common

- name: Check for user-specific provisioning script
  stat: path=/var/www/{{ hostname }}/conf/provision-user
  register: provision_user

- name: Run user-specific provisioning.
  command: /var/www/{{ hostname }}/conf/provision-user
  when: provision_user.stat.exists
  tags: common

- name: Set path to include $HOME/bin for zsh too
  lineinfile: dest=/home/vagrant/.zshrc state=present line='export PATH="$PATH:$REPO/vendor/bin:$HOME/bin"'
  tags: common

- name: Set $PATH to include "vendor/bin" folder
  lineinfile: dest=/home/vagrant/.profile state=present line='export PATH="$PATH:/var/www/mass.local/vendor/bin"'
  tags: common

- name: Set $PATH to include "scripts" folder
  lineinfile: dest=/home/vagrant/.profile state=present line='export PATH="$PATH:/var/www/mass.local/scripts"'
  tags: common

- name: Add "www" alias to "/var/www/mass.local"
  lineinfile: dest=/home/vagrant/.profile state=present line='alias www="cd /var/www/mass.local"'
  tags: common

- name: Configure MASS_PROJECT_DIR variable
  lineinfile: dest=/home/vagrant/.profile state=present line='export MASS_PROJECT_DIR="/var/www/mass.local"'
  tags: common

- name: Copy private key from host to guest (vm)
  template:
    src: ~/.ssh/id_rsa
    dest: /home/vagrant/.ssh/id_rsa
    force: yes
    owner: vagrant
    group: vagrant
    mode: 0400

- name: Copy public key from host to guest (vm)
  template:
    src: ~/.ssh/id_rsa.pub
    dest: /home/vagrant/.ssh/id_rsa.pub
    force: yes
    owner: vagrant
    group: vagrant
    mode: 0400
    
- name: Upgrade composer
  become: True
  command: composer self-update
  tags: common