<?php

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;

/**
 * Implements hook_permission().
 */
function crazyegg_permission() {
  return array(
    'administer crazy egg' => array(
      'title' => t('Administer Crazy Egg'),
      'description' => t('Administer account settings and visibility of Crazy Egg on your site.'),
    ),
  );
}

/**
 * Implements hook_help().
 */
function crazyegg_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.crazyegg':
      return t('<a href="@url">Crazy Egg</a> is an analytics tool that provides website heatmaps and eye tracking.', array('@url' => 'http://www.crazyegg.com'));
  }
}

/**
 * Implements hook_page_attachments().
 */
function crazyegg_page_attachments(array &$attachments) {
  $account_id = \Drupal::config('crazyegg.settings')->get('crazyegg_account_id');
  $crazyegg_enabled = \Drupal::config('crazyegg.settings')->get('crazyegg_enabled');
  $crazyegg_paths = \Drupal::config('crazyegg.settings')->get('crazyegg_paths');

  if ($account_id && $crazyegg_enabled && crazyegg_is_enabled_path($crazyegg_paths)) {
    $account_path = str_pad($account_id, 8, "0", STR_PAD_LEFT);
    $account_path = substr($account_path, 0, 4) . '/' . substr($account_path, 4, 8);
    $account_path = "pages/scripts/" . $account_path . ".js";

    $attachments['#attached']['library'][] = 'crazyegg/crazyegg';
    $attachments['#attached']['drupalSettings']['crazyegg']['crazyegg']['account_path'] = $account_path;
  }
}

/**
 * Checks if the current path is in a list of paths
 */
function crazyegg_is_enabled_path($paths) {
  $url = Url::fromRoute('<current>')->toString();

  return \Drupal::service('path.matcher')->matchPath($url, $paths);
}