node_type_person_status: '1'
node_type_person_pattern: '[node:field_person_first_name] [node:field_person_last_name], [node:field_person_role_title]'
node_type_person_php: 0
submit: 'Save configuration'
form_build_id: form-SkrKFcraZEq92rGZAnNLqG31Rl5y-pALk8dqHaYhEnE
form_token: JR_xvbPyK1Y414igY72fqPux97XbXldsFpIg-vqXurg
form_id: auto_entitylabel_settings_form
op: 'Save configuration'
