access_token_expiration: 300
refresh_token_expiration: 1209600
_core:
  default_config_hash: YJrGmZVEcxxUt1ffTwS_DybfKrbnRkwF1GXzPj-j7aE
public_key: ../credentials/public.key
private_key: ../credentials/private.key
