enabled: 1
send_plugins: {  }
login_plugins: {  }
validation_plugin: tfa_totp
validation_plugin_settings:
  tfa_hotp:
    counter_window: 10
    name_prefix: TFA
  tfa_totp:
    time_skew: 30
    name_prefix: TFA
fallback_plugins:
  tfa_hotp:
    tfa_recovery_code:
      enable: 1
      settings:
        recovery_codes_amount: 9
      weight: -2
  tfa_totp:
    tfa_recovery_code:
      enable: 1
      settings:
        recovery_codes_amount: 9
      weight: -2
help_text: 'Contact support to reset your access'
validation_skip: 3
encryption: two_factor_auth
trust_cookie_expiration: 2592000
cookie_name: TFA
tfa_flood_uid_only: 1
tfa_flood_window: 300
tfa_flood_threshold: 6
_core:
  default_config_hash: MhrA-cxuU_zfd1goV-WFbz-4AFXhlvniyVyDdNBcims
