datalayer.settings:
  type: config_object
  label: Settings
  mapping:
    add_page_meta:
      type: boolean
    output_terms:
      type: boolean
    output_fields:
      type: boolean
    lib_helper:
      type: boolean
    entity_meta:
      type: array
    vocabs:
      type: array
    expose_user_details_roles:
      type: array
