---
- name: PHP | Adjust php.ini memory_limit
  become: True
  lineinfile: dest={{ item }}
              regexp='memory_limit'
              line='memory_limit = {{ php_ini_memory_limit }}'
  with_items:
    - /etc/php/5.6/apache2/php.ini
    - /etc/php/5.6/cli/php.ini
  tags: PHP

- name: PHP | Enable PHP error display
  become: True
  lineinfile: dest={{ item.file }}
              regexp='^{{ item.key }}'
              line='{{ item.key }} = {{ item.value }}'
  with_items:
    - { file: '/etc/php/5.6/apache2/php.ini', key: 'error_reporting', value: "{{ php_ini_error_reporting }}" }
    - { file: '/etc/php/5.6/apache2/php.ini', key: 'display_errors', value: "{{ php_ini_display_errors }}" }
    - { file: '/etc/php/5.6/cli/php.ini', key: 'error_reporting', value: "{{ php_ini_error_reporting }}" }
    - { file: '/etc/php/5.6/cli/php.ini', key: 'display_errors', value: "{{ php_ini_display_errors }}" }
  tags: PHP
