#!/usr/bin/env sh

# Called from circle.yml. Needed for Twig cache busting.
echo "<?php\n\n\$settings['deployment_identifier'] = '$CIRCLE_SHA1';" > ${HOME}/${CIRCLE_PROJECT_REPONAME}/docroot/sites/deployment_id.php
git add ${HOME}/${CIRCLE_PROJECT_REPONAME}/docroot/sites/deployment_id.php
git commit -m "Update deployment identifier"

# Add acquia repo as an additional remote.
git remote add acquia massgov@svn-20994.prod.hosting.acquia.com:massgov.git

# Push the branch. name comes from an environment variable.
git push --force acquia $CIRCLE_BRANCH
