<?php

/**
 * @file
 * Contains mayflower.module.
 */

use Drupal\mayflower\Helper;
use Drupal\mayflower\Prepare\Atoms;
use Drupal\mayflower\Prepare\Molecules;
use Drupal\mayflower\Prepare\Organisms;

/**
 * Implements hook_theme().
 */
function mayflower_theme($existing, $type, $theme, $path) {

  $patterns = mayflower_patternlibrary_paths();

  return [
    'action_seq_list' => [
      'variables' => ['actionSeqLists' => NULL],
      'template' => 'action-seq-list',
      'path' => $patterns['molecules'],
    ],
    'steps_ordered' => [
      'variables' => ['stepsOrdered' => NULL],
      'template' => 'steps-ordered',
      'path' => $patterns['organisms'] . '/by-author',
    ],
    'image_promos' => [
      'variables' => ['imagePromos' => NULL],
      'template' => 'image-promos',
      'path' => $patterns['organisms'] . '/by-author',
    ],
    'callout_links' => [
      'variables' => ['calloutLinks' => NULL],
      'template' => 'callout-links',
      'path' => $patterns['organisms'] . '/by-author',
    ],
    'contact_us' => [
      'variables' => ['contactUs' => NULL],
      'template' => 'contact-us',
      'path' => $patterns['molecules'],
    ],
  ];
}

/**
 * Returns the common patternlibrary paths.
 *
 * @return array
 *   Returns array that contains the paths to the patterlab directories.
 */
function mayflower_patternlibrary_paths() {
  $theme_path = \Drupal::theme()->getActiveTheme()->getPath();
  return [
    'atoms' => $theme_path . '/patterns/atoms',
    'molecules' => $theme_path . '/patterns/molecules',
    'organisms' => $theme_path . '/patterns/organisms',
    'pages' => $theme_path . '/patterns/pages',
  ];
}

/**
 * Prepares variables for image template.
 *
 * Default template: atoms/09-media/image.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - item: An ImageItem object.
 *   - item_attributes: An optional associative array of html attributes to be
 *     placed in the img tag.
 *   - image_style: An optional image style.
 *   - url: An optional \Drupal\Core\Url object.
 */
function mayflower_preprocess_image(array &$variables) {
  $variables['image']['src'] = $variables['uri'];
  $variables['image']['alt'] = $variables['alt'];
  $variables['image']['height'] = $variables['height'];
  $variables['image']['width'] = $variables['width'];
}

/**
 * Implements hook_preprocess_HOOK().
 *
 * @see patterns/molecules/contact-us.twig
 */
function mayflower_preprocess_contact_us(&$variables) {
  $node = $variables['elements']['#node'];

  // Sets the variable structure required for action-seq-list.twig.
  $variables = [
    'theme_hook_original' => $variables['theme_hook_original'],
    'contactUs' => Molecules::prepareContactUs($node, ['display_title' => TRUE]),
  ];
}

/**
 * Returns the variables structure required to render stacked row template.
 *
 * @param object $entity
 *   The object that contains the fields.
 *
 * @see @organisms/by-author/stacked-row-section
 *
 * @return array
 *   Returns an array of items that contain: title, page_content, sidebar.
 */
function mayflower_prepare_stacked_row_sections($entity) {
  // @todo conform with  widgets[] in mass_theme_preprocess_node_org_page
  // ^^ Let the node preprocess configure the necessary child patterns.
  $sections = [];

  $map = [
    'text' => ['body'],
    'social' => ['field_social_links'],
    'featuredActions' => ['field_ref_actions_3'],
    'allActions' => ['field_ref_actions_6'],
    'featuredTopics' => ['field_ref_card_view_6'],
    'relatedLinks' => ['field_ref_orgs'],
  ];

  // Determines which fieldnames to use from the map.
  $fields = Helper::getMappedFields($entity, $map);

  if ($entity->$fields['text']->getValue()) {
    $sideBarSocial = '';

    if (Helper::isFieldPopulated($entity, $fields['social'])) {
      $sideBarSocial = [
        [
          'path' => '@atoms/04-headings/sidebar-heading.twig',
          'data' => Atoms::prepareSidebarHeading(t('Social')),
        ],
        [
          'path' => '@molecules/icon-links.twig',
          'data' => Molecules::prepareIconLinks($entity),
        ],
      ];
    }

    $richTextElements = [];

    if (Helper::isFieldPopulated($entity, $fields['text'])) {
      $richTextElements[] = Atoms::prepareParagraph($entity, ['field' => $fields['text']]);
    }

    $sections[] = [
      'title' => $entity->$fields['text']->getFieldDefinition()->getLabel(),
      'pageContent' => [
        Helper::prepareRichTextElements($richTextElements),
      ],
      'sideBar' => $sideBarSocial,
    ];
  }

  if ($entity->$fields['featuredActions']->getValue() || $entity->$fields['allActions']->getValue()) {
    $action_finder_options = [
      // @todo refactor the strings below to be corresponding field label values
      'title' => t('What Would You Like to Do?'),
      'featuredHeading' => t('Featured:'),
      'generalHeading' => t('How-Tos & Guides:'),
    ];

    $sections[] = [
      'pageContent' => [
        [
          'path' => '@organisms/by-author/action-finder.twig',
          'data' => Organisms::prepareActionFinder($entity, $action_finder_options),
        ],
      ],
    ];
  }

  if ($entity->$fields['featuredTopics']->getValue()) {
    $sectionThreeUp = [
      'heading' => [
        'title' => $entity->$fields['featuredTopics']->getFieldDefinition()->getLabel(),
      ],
    ];

    $sections[] = [
      'pageContent' => [
        [
          'path' => '@organisms/by-author/sections-three-up.twig',
          'data' => [
            'sectionThreeUp' => Organisms::prepareSectionThreeUp($entity->$fields['featuredTopics'], $sectionThreeUp),
          ],
        ],
      ],
    ];
  }

  if ($entity->$fields['relatedLinks']->getValue()) {
    $linkList_options = [
      'heading' => [
        'title' => t('Related Organizations'),
        'type' => 'compHeading',
      ],
    ];

    $sections[] = [
      'pageContent' => [
        [
          'path' => '@organisms/by-author/link-list.twig',
          // @todo Use field label vs string (need to update field label value)
          'data' => [
            'linkList' => Organisms::prepareLinkList($entity, $fields['relatedLinks'], $linkList_options),
          ],
        ],
      ],
    ];
  }

  return $sections;
}

/**
 * Returns the variables structure required for Topic Card.
 *
 * @param object $entity
 *   The object that contains the fields.
 *
 * @return array
 *   Return structured sections.
 */
function mayflower_prepare_subtopic_links($entity) {
  $links = [];
  // Get our Subtopics for each Topic.
  $view_results = views_get_view_result('subtopics', 'section_links', $entity->id());
  foreach ($view_results as $link) {
    $links[] = [
      'href' => $link->_entity->toURL()->toString(),
      'text' => $link->_entity->get('title')->value,
    ];
  }

  return $links;
}
